# Generated by Django 3.2.12 on 2022-04-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
                ('telephone', models.CharField(max_length=50, verbose_name='telephone')),
                ('text', models.TextField(max_length=300, verbose_name='text')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
