# Generated by Django 3.2.13 on 2022-06-15 23:16

import ckeditor.fields
import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='images', verbose_name='image')),
                ('content', ckeditor.fields.RichTextField(verbose_name='content')),
                ('publish_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'ordering': ['title'],
                'unique_together': {('publish_on', 'slug')},
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager('publish_on')),
            ],
        ),
    ]
