# Generated by Django 3.2.13 on 2022-06-27 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0002_auto_20220616_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('description_short', models.TextField(blank=True, verbose_name='description short')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True, verbose_name='slug')),
                ('meta_keywords', models.CharField(blank=True, max_length=160, verbose_name='meta keywords')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='meta description')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='category_event/', verbose_name='image')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='title')),
            ],
            options={
                'verbose_name': 'event category',
                'verbose_name_plural': 'event categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a11y_accesss', models.BooleanField(default=False, verbose_name='access')),
                ('a11y_wc', models.BooleanField(default=False, verbose_name='wc')),
                ('a11y_info', models.BooleanField(default=False, verbose_name='information')),
                ('a11y_service', models.BooleanField(default=False, verbose_name='accesibility full')),
                ('a11y_text', models.TextField(blank=True, default='', null=True, verbose_name='aclarations')),
                ('min_age', models.CharField(blank=True, max_length=120, verbose_name='min age')),
                ('max_age', models.CharField(blank=True, max_length=120, verbose_name='max age')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='requirements')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='price')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='link')),
                ('description_short', models.TextField(blank=True, verbose_name='description short')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('starred', models.BooleanField(default=False, verbose_name='starred')),
                ('child', models.BooleanField(default=False, verbose_name='child')),
                ('limited_seating', models.BooleanField(default=False, verbose_name='limited seating')),
                ('registration_required', models.BooleanField(default=False, verbose_name='registration required')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('f', 'Finished'), ('o', 'On hold'), ('p', 'Published'), ('d', 'Draft')], default='d', max_length=1, verbose_name='Publication status')),
                ('meta_keywords', models.CharField(blank=True, max_length=160, verbose_name='meta keywords')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='meta title')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='meta description')),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='longitude')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='slug')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='frontend.categoryevent', verbose_name='category')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
    ]
