# Generated by Django 3.2.13 on 2022-06-27 20:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_categoryevent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='events/images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='categoryevent',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image'),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(max_length=255, verbose_name='alt')),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='blog_galleries/', verbose_name='image')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='frontend.event', verbose_name='event')),
            ],
        ),
    ]
