# Generated by Django 3.2.13 on 2022-06-29 21:14

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20220627_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryevent',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='category_event/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
