# Generated by Django 3.2.13 on 2022-10-22 14:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20220629_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 22, 14, 35, 50, 856742, tzinfo=utc)),
        ),
    ]
