# Generated by Django 3.2.13 on 2022-10-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_page_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='modified_at'),
        ),
        migrations.AlterField(
            model_name='page',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
    ]
