# Generated by Django 3.2.13 on 2022-10-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20221022_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-published_at',), 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
    ]
