# Generated by Django 3.2.13 on 2023-01-31 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_description',
            field=models.TextField(default='', help_text='con un máximo de 140 caracteres', max_length=140, verbose_name='meta-description'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.TextField(default='', help_text='con un máximo de 55 caracteres', max_length=55, verbose_name='meta-title'),
        ),
    ]
