# Generated by Django 3.2.13 on 2023-02-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20230131_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='text_show_date',
            field=models.TextField(blank=True, default='', null=True, verbose_name='texto de Fecha'),
        ),
        migrations.AddField(
            model_name='event',
            name='text_show_geo',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Texto de Lugar'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_purchase_link',
            field=models.URLField(blank=True, help_text='Link para comprar la entrada al evento', null=True, verbose_name='link de compra'),
        ),
    ]
