# Generated by Django 4.2 on 2023-04-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_auto_20230205_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryevent',
            name='meta_description',
            field=models.TextField(help_text='entre de 120 a 330 carácteres, Obligatorio para el SEO', verbose_name='meta_description'),
        ),
        migrations.AlterField(
            model_name='categoryevent',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='lista de palabras o frases claves, separados por una coma(,). Ejemplo: APILAD, Evento Público, etc', null=True, verbose_name='meta_keywords'),
        ),
        migrations.AlterField(
            model_name='categoryevent',
            name='meta_title',
            field=models.CharField(help_text='máximo de 65 carácteres, obligatorio para el SEO', max_length=65, verbose_name='meta_title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='meta_description',
            field=models.TextField(help_text='entre de 120 a 330 carácteres, Obligatorio para el SEO', verbose_name='meta_description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='lista de palabras o frases claves, separados por una coma(,). Ejemplo: APILAD, Evento Público, etc', null=True, verbose_name='meta_keywords'),
        ),
        migrations.AlterField(
            model_name='event',
            name='meta_title',
            field=models.CharField(help_text='máximo de 65 carácteres, obligatorio para el SEO', max_length=65, verbose_name='meta_title'),
        ),
    ]
