# Generated by Django 4.2 on 2023-04-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_alter_categoryevent_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryevent',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text="lista de palabras o frases claves, entre comillas simples y separados por una coma (,). Ejemplo: 'APILAD', 'Evento Público', 'etc'", null=True, verbose_name='meta_keywords'),
        ),
        migrations.AlterField(
            model_name='categoryevent',
            name='meta_title',
            field=models.TextField(help_text='máximo de 65 carácteres, obligatorio para el SEO', max_length=65, verbose_name='meta_title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text="lista de palabras o frases claves, entre comillas simples y separados por una coma (,). Ejemplo: 'APILAD', 'Evento Público', 'etc'", null=True, verbose_name='meta_keywords'),
        ),
        migrations.AlterField(
            model_name='event',
            name='meta_title',
            field=models.TextField(help_text='máximo de 65 carácteres, obligatorio para el SEO', max_length=65, verbose_name='meta_title'),
        ),
    ]
