# Generated by Django 4.2.3 on 2023-09-26 14:29

import core.utils
from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_page_meta_keywords_alter_categoryevent_meta_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='promotions/images/', validators=[core.utils.validate_file_extension, core.utils.validate_image], verbose_name='image')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('link', models.URLField(blank=True, help_text='Link de evento', null=True, verbose_name='link')),
                ('alt', models.CharField(blank=True, help_text='Texto alternativo para la imagen', max_length=255, null=True, verbose_name='alt')),
            ],
            options={
                'verbose_name': 'promoción',
                'verbose_name_plural': 'promociones',
                'ordering': ('order',),
            },
        ),
    ]
