# Generated by Django 4.2.3 on 2023-09-26 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_promotions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promotions',
            new_name='Promotion',
        ),
    ]
