# Generated by Django 4.2 on 2024-03-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0016_promotion_description_promotion_description_short_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ("order",),
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="order",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="order"
            ),
        ),
    ]
