# Generated by Django 4.2.9 on 2024-07-06 09:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_alter_event_options_event_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryevent',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.CharField(blank=True, default=0, max_length=40, verbose_name='latitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.CharField(blank=True, default=0, max_length=40, verbose_name='longitude'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='description'),
        ),
    ]
